name: Frontend e2e w/ back-end

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      # Checkout frontend (this repo)
      - name: Checkout frontend
        uses: actions/checkout@v4

      # Setup Node and install deps
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # Install Playwright and OS deps
      - name: Setup Playwright
        run: npx playwright install chromium --only-shell # --with-deps

      # Run tests (Playwright will start the web server defined in playwright.config)
      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: test-results
          retention-days: 7
